@php
    if(empty($title)){
        $title  = null;
    }
@endphp
<x-print-layout :title="$title">
    <div class="row">
        <div class="col-12">
            @php
                /**
               * @var \App\Models\Transactions\Invoice $invoice
               * @var \App\Models\Transactions\InvoicePaymentReceipt $receipt
               */
               $invoice = $receipt->invoice;
               $bill_to = $invoice->university;
            @endphp
            <table style="width: 100%">
                <tbody>
                <tr>
                    <td style="width: 35%; vertical-align: baseline">
                        <img src="{{AppConst::SITE_LOGOS}}/Logo-stars-v1.png" style="width: 100%">
                    </td>
                    <td style="text-align: right">
                        <h1 class="h1"><b>@lang('Receipt')</b></h1>
                        <p class="h4">@lang('Receipt#'){{$receipt->receipt_number}}</p>
                        <p class="h4">@lang('Account ID'): {{$invoice->created_by_id}}</p>
                    </td>
                </tr>
                <tr>
                    <td style="width: 35%">
                        <h4 class="h4"><b>@lang('UNIRANKS Inc')</b></h4>
                        <p class="h5" style="margin-bottom: 0; margin-top: 0;">@lang('USA, New York')</p>
                        <p class="h5"
                           style="margin-bottom: 0; margin-top: 0;">@lang('1330 Avenue of the Americas, 23rd Floor New York, NY 10019')</p>
                        <p class="h5" style="margin-bottom: 0; margin-top: 0;">1212 653 0628</p>
                    </td>
                    <td style="text-align: right">
                        <h4 class="h4"><b>@lang('Bill To')</b></h4>
                        <p class="h5">{{$bill_to?->translated_name ?: $bill_to?->university_name}}</p>
                        <p class="h5">{{$bill_to->country?->translated_name ?: $bill_to->country?->country_name}}</p>
                        <p class="h5">@lang('Issued Date'): {{$receipt->created_at?->toDateString()}}</p>
                        <p class="h5">@lang('Currency'): {{$invoice->currency->name}} ({{$invoice->currency->code}})</p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <table style="width: 100%; border: solid 1px #ccced0; border-collapse: collapse">
                            <thead style="background: #1c345a !important; print-color-adjust: exact">
                            <!--Heading Row-->
                            <tr style="background: #1c345a !important; ">
                                <td style="width: 70%; color: white; padding: .5rem .5rem;
                                 border-bottom-width: 1px;">@lang('Description')</td>
                                <td style="text-align: right; color: white;  padding: .5rem .5rem;
                                 border-bottom-width: 1px;">@lang('Amount')</td>
                            </tr>
                            <!--End Heading row-->
                            </thead>
                            <tbody>
                            <!--Row Start-->
                            <tr>
                                <td style="padding: .5rem .5rem;
                                 border-bottom: 1px solid #ccced0;">
                                    {{$receipt->description ?: ("For Invoice# INV-".$invoice?->invoice_number) }}
                                </td>
                                <td style="text-align: right; padding: .5rem .5rem;
                                     border-bottom: 1px solid #ccced0;">{{$invoice?->currency?->code}} {{number_format($receipt->amount,2)}}</td>
                            </tr>
                            <!--Row Start-->
                            <tr>
                                <td colspan="2" style="padding: .5rem .5rem;
                                 border-bottom-width: 1px;">
                                    @lang('Payment Method'):{{$invoice?->paymentMethod?->title ?? "---"}}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="2">
                        <div class="footer-space">&nbsp;</div>
                    </td>
                </tr>
                </tfoot>
            </table>
            {{--display: flex;
  justify-content: end;
  flex-flow: column;--}}
            <div class="footer" style="text-align: center;">
                @lang('This receipt of payment has been automatically generated by the system. ')
            </div>
        </div>
        <!-- CONTAINER CLOSED -->
    </div>
</x-print-layout>
