<div>
    <div class="row">
        <div class="col-12">
            <div x-data="{ showFilters:false }" class="w-100">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between blue">
                        <div class="h5 blue">@lang('System Invoice')</div>
                        <a href="javascript:void(0)" onclick="printDivContent('{{route('admin.account.downloadReceipt',$receipt->id)}}')"   class="a-underline blue" >
                            @lang('Print Invoice') <i class="fa-solid fa-print pointer"></i>
                        </a>
                    </div>
                </div>
            </div>
            @php
                /**
                * @var \App\Models\Transactions\Invoice $invoice
                * @var \App\Models\Transactions\InvoicePaymentReceipt $receipt
                */
                $invoice = $receipt->invoice;
                $bill_to = $invoice->university;
            @endphp
            <div class="card mt-3">
                <div class="card-body p-0">
                    <div class="d-flex justify-content-between px-4 pt-3">
                        <div class="w-35">
                            <img src="{{AppConst::SITE_LOGOS}}/Logo-stars-v1.png" style="width: 100%">
                        </div>
                        <div class="w-auto text-end blue">
                            <h1 class="h1"><b>@lang('Receipt')</b></h1>
                            <p class="h4">@lang('Receipt#'){{$receipt->receipt_number}}</p>
                            <p class="h4">@lang('Account ID'): {{$invoice->created_by_id}}</p>
                        </div>
                    </div>
                    <div class="d-flex justify-content-between mt-3 px-4">
                        <div class="w-35 blue">
                            <h4 class="h4"><b>@lang('UNIRANKS Inc')</b></h4>
                            <p class="h5">@lang('USA, New York')</p>
                            <p class="h5">@lang('1330 Avenue of the Americas, 23rd Floor New York, NY 10019')</p>
                            <p class="h5">1212 653 0628</p>
                        </div>
                        <div class="w-auto text-end blue">
                            <h4 class="h4"><b>@lang('Bill To')</b></h4>
                            <p class="h5">{{$bill_to?->translated_name ?: $bill_to?->university_name}}</p>
                            <p class="h5">{{$bill_to->country?->translated_name ?: $bill_to->country?->country_name}}</p>
                            <p class="h5">@lang('Issued Date'): {{$receipt->created_at?->toDateString()}}</p>
                            <p class="h5">@lang('Currency'): {{$invoice->currency->name}} ({{$invoice->currency->code}})</p>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table bg-light blue invoices-table">
                            <thead class="primary-bg ">
                            <!--Heading Row-->
                            <tr>
                                <td class="w-70 text-light">@lang('Description')</td>
                                <td class="text-end text-light">@lang('Amount')</td>
                            </tr>
                            <!--End Heading row-->
                            </thead>
                            <tbody>
                            <!--Row Start-->
                            <tr>
                                <td>{{$receipt->description}}</td>
                                <td class="text-end">{{$invoice->currency->code}} {{number_format($receipt->amount,2)}} </td>
                            </tr>
                            <!--Row Start-->
                            <tr>
                                <td colspan="2">@lang('Payment Method'):{{$invoice->paymentMethod?->title ?? "---"}}</td>
                            </tr>
                            </tbody>
                        </table>
                        <div class="text-center blue px-4 pb-3" style="margin-top: 8rem">
                            @lang('This receipt of payment has been automatically generated by the system.')
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- CONTAINER CLOSED -->
        @push(AppConst::PUSH_JS)
            <script type="text/javascript">
                function printDivContent(url) {
                    let newWin = window.open(url, '', 'height=650, width=650');
                }
            </script>
        @endpush
    </div>
</div>
